# Sentiment Classification


### Generate Word Embeddings and retrieve outputs of each layer with Keras based on Classification task

Word embeddings are a type of word representation that allows words with similar meaning to have a similar representation.

It is a distributed representation for text that is perhaps one of the key breakthroughs for the impressive performance of deep learning methods on challenging natural language processing problems.

We willl use the imdb dataset to learn word embeddings as we train our dataset. This dataset contains 25,000 movie reviews from IMDB, labeled with sentiment (positive or negative). 



### Dataset

`from keras.datasets import imdb`

Dataset of 25,000 movies reviews from IMDB, labeled by sentiment (positive/negative). Reviews have been preprocessed, and each review is encoded as a sequence of word indexes (integers). For convenience, the words are indexed by their frequency in the dataset, meaning the for that has index 1 is the most frequent word. Use the first 20 words from each review to speed up training, using a max vocab size of 10,000.

As a convention, "0" does not stand for a specific word, but instead is used to encode any unknown word.


### Aim

1. Import test and train data  
2. Import the labels ( train and test) 
3. Get the word index and then Create key value pair for word and word_id. (12.5 points)
4. Build a Sequential Model using Keras for Sentiment Classification task. (10 points)
5. Report the Accuracy of the model. (5 points)  
6. Retrive the output of each layer in keras for a given single test sample from the trained model you built. (2.5 points)


#### Usage:

In [1]:
from keras.datasets import imdb
import numpy as np

np_load_old = np.load

np.load = lambda *a, **k: np_load_old(*a, allow_pickle=True, **k)
vocab_size = 10000 #vocab size

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size) # vocab_size is no.of words to consider from the dataset, ordering based on frequency.

Using TensorFlow backend.


17465344/17464789 [==============================] - 2s 0us/step


In [0]:
import pandas as pd

In [3]:
len(x_train)

25000

In [0]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 300  #number of word used from each review

In [0]:
#load dataset as a list of ints
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen,padding='post')
x_test =  pad_sequences(x_test, maxlen=maxlen,padding='post')

In [0]:
# Considering only first 20 words in each review to speed up training

In [0]:
x_train = x_train[:,0:20]

In [0]:
x_test = x_test[:,0:20]

In [7]:
x_train

array([[   1,   14,   22, ...,    0,    0,    0],
       [   1,  194, 1153, ...,    0,    0,    0],
       [   1,   14,   47, ...,    0,    0,    0],
       ...,
       [   1,   11,    6, ...,    0,    0,    0],
       [   1, 1446, 7079, ...,    0,    0,    0],
       [   1,   17,    6, ...,    0,    0,    0]], dtype=int32)

In [21]:
x_train.shape

(25000, 20)

### Key and Value pair

In [0]:
word_n_word_index_dict = imdb.get_word_index()

In [10]:
word_n_word_index_dict

{'fawn': 34701,
 'tsukino': 52006,
 'nunnery': 52007,
 'sonja': 16816,
 'vani': 63951,
 'woods': 1408,
 'spiders': 16115,
 'hanging': 2345,
 'woody': 2289,
 'trawling': 52008,
 "hold's": 52009,
 'comically': 11307,
 'localized': 40830,
 'disobeying': 30568,
 "'royale": 52010,
 "harpo's": 40831,
 'canet': 52011,
 'aileen': 19313,
 'acurately': 52012,
 "diplomat's": 52013,
 'rickman': 25242,
 'arranged': 6746,
 'rumbustious': 52014,
 'familiarness': 52015,
 "spider'": 52016,
 'hahahah': 68804,
 "wood'": 52017,
 'transvestism': 40833,
 "hangin'": 34702,
 'bringing': 2338,
 'seamier': 40834,
 'wooded': 34703,
 'bravora': 52018,
 'grueling': 16817,
 'wooden': 1636,
 'wednesday': 16818,
 "'prix": 52019,
 'altagracia': 34704,
 'circuitry': 52020,
 'crotch': 11585,
 'busybody': 57766,
 "tart'n'tangy": 52021,
 'burgade': 14129,
 'thrace': 52023,
 "tom's": 11038,
 'snuggles': 52025,
 'francesco': 29114,
 'complainers': 52027,
 'templarios': 52125,
 '272': 40835,
 '273': 52028,
 'zaniacs': 52130,

## Build Keras Embedding Layer Model
We can think of the Embedding layer as a dicionary that maps a index assigned to a word to a word vector. This layer is very flexible and can be used in a few ways:

* The embedding layer can be used at the start of a larger deep learning model. 
* Also we could load pre-train word embeddings into the embedding layer when we create our model.
* Use the embedding layer to train our own word2vec models.

The keras embedding layer doesn't require us to onehot encode our words, instead we have to give each word a unqiue intger number as an id. For the imdb dataset we've loaded this has already been done, but if this wasn't the case we could use sklearn [LabelEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html).

In [0]:
from keras.models import Sequential

In [0]:
from keras.layers import Embedding, Flatten, LSTM, Dense, Dropout, Masking, Bidirectional
import numpy as np

In [0]:
model = Sequential()

In [0]:

model.add(Embedding(vocab_size + 1,###nedd to handle index between 0 and 10000
                    32,#embedding_vector_length,###50 embedding
                    input_length=20,#input_length=max_review_length,##300 max lenght we got above
                    weights=None, #Pre-trained embedding
                    trainable=True) #We do not want to change embedding
                   )
# Recurrent layer
model.add(LSTM(1, return_sequences=False, dropout=0.1,recurrent_dropout=0.1))
#model.add(Flatten())

In [0]:

model.add(Dense(1, activation='sigmoid'))

In [0]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [66]:
# summarize the model
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, 20, 32)            320032    
_________________________________________________________________
lstm_5 (LSTM)                (None, 1)                 136       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 2         
Total params: 320,170
Trainable params: 320,170
Non-trainable params: 0
_________________________________________________________________


In [67]:
# fit the model
model.fit(x_train, y_train, epochs=10, verbose=0)

In [68]:
loss, accuracy = model.evaluate(x_train, y_train, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 91.332000


In [69]:
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 66.372000


## Retrive the output of each layer in keras for a given single test sample from the trained model you built

In [0]:
from keras import Model

In [74]:
model.get_layer('embedding_8')

In [75]:
x_test[0]

array([   1,  591,  202,   14,   31,    6,  717,   10,   10,    2,    2,
          5,    4,  360,    7,    4,  177, 5760,  394,  354], dtype=int32)

In [0]:
embedding_layer_model = Model(inputs = model.input, outputs= model.get_layer('embedding_8').output)

In [80]:
x_test

array([[   1,  591,  202, ..., 5760,  394,  354],
       [   1,   14,   22, ...,  114,    9,   55],
       [1239, 5189,  137, ..., 8014,   37,  272],
       ...,
       [   1,   13, 1408, ...,   45,  184,   78],
       [   1,   11,  119, ...,   86,  107,    8],
       [   1,    6,   52, ...,   47,    6, 3482]], dtype=int32)

In [81]:
x_test[0:1,:].shape

(1, 20)

In [82]:
embedding_layer_model.predict(x_test[0:1,:])

array([[[-3.34862843e-02, -1.05691232e-01,  2.66448408e-02,
          1.41437724e-01,  6.47306889e-02, -1.54052451e-01,
          1.60309196e-01,  1.19409576e-01,  8.21004286e-02,
         -4.79380637e-02, -3.94492559e-02,  1.17282178e-02,
          2.08298638e-02, -1.06348224e-01, -2.64750365e-02,
          2.02940360e-01, -9.95476693e-02,  5.45947179e-02,
          2.57859230e-02, -3.42274308e-01,  2.84960896e-01,
          2.22846180e-01,  2.52790060e-02,  2.45542135e-02,
          1.48766078e-02,  8.78482386e-02, -6.12833202e-02,
          7.75227770e-02, -4.68959063e-02,  5.33895940e-02,
         -8.85549858e-02, -1.28834313e-02],
        [ 9.76081043e-02, -7.27125257e-02,  5.05042560e-02,
         -8.03218409e-03, -6.42189831e-02,  3.25085670e-02,
         -6.91763610e-02,  3.73789109e-02, -1.88498124e-02,
          2.03966368e-02, -4.77204360e-02,  1.01275221e-01,
         -1.39813535e-02, -1.78362913e-02,  6.08796068e-02,
         -7.93932453e-02, -3.32672708e-02,  1.86202526e-

In [0]:
flatten_layer_model = Model(inputs = model.input, outputs= model.get_layer('dense_6').output)

In [84]:
flatten_layer_model.predict(x_test[0:1,:])

array([[0.02155217]], dtype=float32)